runtime: go113
env_variables:
      ADMIN_SECRET: "CflFPa89BzSiVdamikDavDBpKtC9A2zk"
      API_KEY: "b95d785d64a4e396406586a175e7955c"
      DEFAULT_IMAGE_FOLDER: "Data/Gallery"
      DEFAULT_DATASTORE_FILEPATH: "Data/DB"
      DEFAULT_DATASTORE_FILE: "moviedb.db"